export const DummyUserData =
{
  userData:  [
    {
      name: 'John Doe',
      email: 'john.doe@example.com',
      profilePic: 'https://example.com/john-doe-pic.jpg',
      age: 30,
      collegeName: 'ABC University',
      address: '123 Main St, Cityville',
      pincode: '12345',
      linkedinUrl: 'https://www.linkedin.com/in/johndoe/',
      githubUrl: 'https://github.com/johndoe',
    },
    {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      profilePic: 'https://example.com/jane-smith-pic.jpg',
      age: 25,
      collegeName: 'XYZ College',
      address: '456 Oak St, Townsville',
      pincode: '67890',
      linkedinUrl: 'https://www.linkedin.com/in/janesmith/',
      githubUrl: 'https://github.com/janesmith',
    },
    {
      name: 'Bob Johnson',
      email: 'bob.johnson@example.com',
      profilePic: 'https://example.com/bob-johnson-pic.jpg',
      age: 40,
      collegeName: 'DEF Institute',
      address: '789 Pine St, Villageton',
      pincode: '54321',
      linkedinUrl: 'https://www.linkedin.com/in/bobjohnson/',
      githubUrl: 'https://github.com/bobjohnson',
    },
    // Additional data
    {
      name: 'Alice Williams',
      email: 'alice.williams@example.com',
      profilePic: 'https://example.com/alice-williams-pic.jpg',
      age: 28,
      collegeName: 'GHI College',
      address: '101 Cedar St, Hamletville',
      pincode: '98765',
      linkedinUrl: 'https://www.linkedin.com/in/alicewilliams/',
      githubUrl: 'https://github.com/alicewilliams',
    },
    {
      name: 'Charlie Brown',
      email: 'charlie.brown@example.com',
      profilePic: 'https://example.com/charlie-brown-pic.jpg',
      age: 35,
      collegeName: 'JKL University',
      address: '202 Maple St, Villagetown',
      pincode: '13579',
      linkedinUrl: 'https://www.linkedin.com/in/charliebrown/',
      githubUrl: 'https://github.com/charliebrown',
    },
    {
      name: 'Eva Martinez',
      email: 'eva.martinez@example.com',
      profilePic: 'https://example.com/eva-martinez-pic.jpg',
      age: 32,
      collegeName: 'MNO Institute',
      address: '303 Birch St, Countryside',
      pincode: '24680',
      linkedinUrl: 'https://www.linkedin.com/in/evamartinez/',
      githubUrl: 'https://github.com/evamartinez',
    },
    {
      name: 'David Lee',
      email: 'david.lee@example.com',
      profilePic: 'https://example.com/david-lee-pic.jpg',
      age: 33,
      collegeName: 'PQR College',
      address: '404 Elm St, Metropolis',
      pincode: '86420',
      linkedinUrl: 'https://www.linkedin.com/in/davidlee/',
      githubUrl: 'https://github.com/davidlee',
    },
    {
      name: 'Grace Turner',
      email: 'grace.turner@example.com',
      profilePic: 'https://example.com/grace-turner-pic.jpg',
      age: 29,
      collegeName: 'STU University',
      address: '505 Oak St, Hamletville',
      pincode: '97531',
      linkedinUrl: 'https://www.linkedin.com/in/graceturner/',
      githubUrl: 'https://github.com/graceturner',
    },
    {
      name: 'Henry White',
      email: 'henry.white@example.com',
      profilePic: 'https://example.com/henry-white-pic.jpg',
      age: 37,
      collegeName: 'VWX Institute',
      address: '606 Pine St, Cityville',
      pincode: '75309',
      linkedinUrl: 'https://www.linkedin.com/in/henrywhite/',
      githubUrl: 'https://github.com/henrywhite',
    },
    {
      name: 'Ivy Adams',
      email: 'ivy.adams@example.com',
      profilePic: 'https://example.com/ivy-adams-pic.jpg',
      age: 26,
      collegeName: 'YZA College',
      address: '707 Cedar St, Townsville',
      pincode: '10293',
      linkedinUrl: 'https://www.linkedin.com/in/ivyadams/',
      githubUrl: 'https://github.com/ivyadams',
    },
  ]
}
  

  